  stages:
    - build
    - deploy

  variables:
    TAG: $CI_PIPELINE_ID
    FILES_PATH: /mnt/build-images/k8s/wallid-listenerid

  build:
    stage: build
    environment: development
    only:
    - master
    tags:
    - listenerID
    - docker image
    script:
    - $FILES_PATH/build-image.sh
